### ISSUE TITLE
What is the meaning of PEKshort?

### ISSUE THREAD

**Issue by arduino-man** [spaceAngel/cyberWatch#1]
I am curious, what is the meaning of PEKshort inside CyberWatch.cpp?

Love the cyberwatch OS btw

**Comment by spaceAngel** [comment]
PEKshort means short press (approx <1s) of the button on the right side of watches. (In my system used for start/stop/reset stopwatch, turn on "allways on" feature on clockfaces component and so on.

PEKlong means press this button a hold it pressed - ususally used for turining off.

Is that clear?

**Comment by arduino-man** [comment]
Absolutely clear. Thank you. 

May I ask what the PEK portion stands for?
It's really just curiosity.

Thanks a lot.

**Comment by spaceAngel** [comment]
As i said, I use it as "control button" in case i want to prevent "randomly touching" display, but I need user itneraction - eg. start/stop stopwatch
.

**Comment by arduino-man** [comment]
Thanks for responding. I think I didn't explain myself properly, sorry.
 I understand the purpose of the button.

I am curious about the meaning of the variable name.

Was does the letters P.E.K stand for? I am curious as to why it is called PEKshort and not something else.

Thank you

**Comment by spaceAngel** [comment]
I don't know real meaning of the "PEK" term. It's used in axp202 library (library for working with power source).

Sorry, i don!t know the answer :-(

**Comment by spaceAngel** [comment]
Oh, just google it. 

Power Extender Kit

https://homeinspectioninsider.com/ecobee-power-extender-kit/

**Comment by arduino-man** [comment]
Thank you very much good sir.

**Comment by arduino-man** [comment]
After some googling I confirmed that PEK actually stands for Power Enable Key :)

Cheers
