### ISSUE TITLE
T watch v2

### ISSUE THREAD

**Issue by baptistedftn** [spaceAngel/cyberWatch#4]
Is it possible to use this code with the t-watch 2020v2?

**Comment by spaceAngel** [comment]
Don't know, sorry. In theory - yes, but must be tested. Maybe v2 doesnt have step counter/move sensor ?

**Comment by baptistedftn** [comment]
I've got this error
`src/CyberWatch.cpp: In member function 'void CyberWatch::init()':
src/CyberWatch.cpp:30:25: error: 'class TTGOClass' has no member named 'motor_begin'; did you mean 'sdcard_begin'?
  TTGOClass::getWatch()->motor_begin();
                         ^~~~~~~~~~~
                         sdcard_begin
*** [.pio/build/ttgo-t-watch/src/CyberWatch.cpp.o] Error 1
src/System/MotorController.cpp: In static member function 'static void MotorController::vibrate(uint8_t)':
src/System/MotorController.cpp:9:25: error: 'class TTGOClass' has no member named 'motor'
  TTGOClass::getWatch()->motor->onec(100);
                         ^~~~~
src/System/MotorController.cpp:12:26: error: 'class TTGOClass' has no member named 'motor'
   TTGOClass::getWatch()->motor->onec(150);
                          ^~~~~
*** [.pio/build/ttgo-t-watch/src/System/MotorController.cpp.o] Error 1
============================================= [FAILED] Took 4.12 seconds =============================================
`

**Comment by spaceAngel** [comment]
Ok, It seems that v2 has not motor for vibrate. I will fix this in near future - add  support for v2. When this will be done, i will close this issue. :-)

**Comment by baptistedftn** [comment]
Thank you for your quick response

**Comment by spaceAngel** [comment]
hey there, solved problem with motor.  Please test, if there will be everything ok, close this issue :)

**Comment by baptistedftn** [comment]
It works, thank you.
